### ISSUE TITLE
Panic when showing the api server, but no shoot in target (user errors should not end in panics)

### ISSUE THREAD

**Issue by vlerenc** [gardener/gardenctl#11]
```
$ gardenctl get target
target:
- kind: garden
  name: dev
- kind: seed
  name: seed-openstack-dev

$ gardenctl show api
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/gardener/gardenctl/cmd.showPod(0x1d3328f, 0xe, 0x1d2be90, 0x4)
	/Users/d043832/go/src/github.com/gardener/gardenctl/cmd/show.go:153 +0x61d
github.com/gardener/gardenctl/cmd.showAPIServer()
	/Users/d043832/go/src/github.com/gardener/gardenctl/cmd/show.go:173 +0x4b
github.com/gardener/gardenctl/cmd.glob..func14(0x2497f60, 0xc42031b6f0, 0x1, 0x1)
	/Users/d043832/go/src/github.com/gardener/gardenctl/cmd/show.go:48 +0x39c
github.com/gardener/gardenctl/vendor/github.com/spf13/cobra.(*Command).execute(0x2497f60, 0xc42031b680, 0x1, 0x1, 0x2497f60, 0xc42031b680)
	/Users/d043832/go/src/github.com/gardener/gardenctl/vendor/github.com/spf13/cobra/command.go:603 +0x22b
github.com/gardener/gardenctl/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x24965e0, 0x0, 0x0, 0x100000000000000)
	/Users/d043832/go/src/github.com/gardener/gardenctl/vendor/github.com/spf13/cobra/command.go:689 +0x339
github.com/gardener/gardenctl/vendor/github.com/spf13/cobra.(*Command).Execute(0x24965e0, 0xc, 0x0)
	/Users/d043832/go/src/github.com/gardener/gardenctl/vendor/github.com/spf13/cobra/command.go:648 +0x2b
github.com/gardener/gardenctl/cmd.Execute()
	/Users/d043832/go/src/github.com/gardener/gardenctl/cmd/root.go:60 +0x4f8
main.main()
	/Users/d043832/go/src/github.com/gardener/gardenctl/gardenctl.go:20 +0x20
```

**Comment by DockToFuture** [comment]
Thank you for providing feedback on Gardenctl. Issue is fixed.
