### ISSUE TITLE
Gardenctl panics when accessing node that has not joined the cluster

### ISSUE THREAD

**Issue by schrodit** [gardener/gardenctl#130]
**Describe the bug**
Gardenctl panics when trying to ssh into a node that has not yet joined the cluster.

```
Downloaded id_rsa key
Fetching coreos AMI
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb0 pc=0x1dabd58]

goroutine 1 [running]:
github.com/gardener/gardenctl/pkg/cmd.fetchAWSImageIDByInstancePrivateIP(0x7ffeefbff7c6, 0xc, 0xc000601538, 0x1)
	/go/src/pkg/cmd/ssh.go:317 +0x238
github.com/gardener/gardenctl/pkg/cmd.sshToAWSNode(0x7ffeefbff7c6, 0xc, 0xc0000842a0, 0x61)
	/go/src/pkg/cmd/ssh.go:140 +0xb4
github.com/gardener/gardenctl/pkg/cmd.NewSSHCmd.func1(0xc0000e4280, 0xc0002f0090, 0x1, 0x1, 0x0, 0x0)
	/go/src/pkg/cmd/ssh.go:117 +0x595
github.com/spf13/cobra.(*Command).execute(0xc0000e4280, 0xc0002f0040, 0x1, 0x1, 0xc0000e4280, 0xc0002f0040)
	/go/src/vendor/github.com/spf13/cobra/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0x2c5f980, 0x1d, 0xc000042740, 0x1d)
	/go/src/vendor/github.com/spf13/cobra/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/vendor/github.com/spf13/cobra/command.go:864
github.com/gardener/gardenctl/pkg/cmd.Execute()
	/go/src/pkg/cmd/root.go:104 +0x2ae
main.main()
	/go/src/cmd/gardenctl/main.go:20 +0x20
```
https://github.com/gardener/gardenctl/blob/master/pkg/cmd/ssh.go#L317

The same command is working for gardenctl 0.11.0

**To Reproduce**
1. gardenctl ssh <node ip from aws console>

**Expected behavior**
SSH into node or error message that states that the node has not joined the cluster and is unable to be accessed.

**Gardenctl Version (please complete the following information):**
 - 0.13.0

**Comment by ialidzhikov** [comment]
Thanks for reporting!
This should be fixed with #131. If you manage to reproduce with the master branch g/gctl, please reopen.
