### ISSUE TITLE
`gardenctl ls issues` causes a runtime panic

### ISSUE THREAD

**Issue by dansible** [gardener/gardenctl#176]
**Describe the bug**
Running `gardenctl ls isssues` causes a runtime panic on [v0.16.0](https://github.com/gardener/gardenctl/releases/tag/v0.16.0). 

This occurs regardless of what project/seed/shoot is currently targeted.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1da3d69]

goroutine 1 [running]:
github.com/gardener/gardenctl/pkg/cmd.getIssues(0x227e3c0, 0xc0000ca000, 0x227e3e0, 0xc0000ca008, 0x227e3e0, 0xc0000ca010)
	/Users/d068290/go/src/github.com/gardener/gardenctl/pkg/cmd/ls.go:211 +0x39
github.com/gardener/gardenctl/pkg/cmd.NewLsCmd.func1(0xc0001ddb80, 0xc000297fe0, 0x1, 0x1, 0x0, 0x0)
	/Users/d068290/go/src/github.com/gardener/gardenctl/pkg/cmd/ls.go:78 +0x658
github.com/spf13/cobra.(*Command).execute(0xc0001ddb80, 0xc000297f90, 0x1, 0x1, 0xc0001ddb80, 0xc000297f90)
	/Users/d068290/go/src/github.com/gardener/gardenctl/vendor/github.com/spf13/cobra/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0x2ccbf00, 0x1d, 0xc0000c99c0, 0x36)
	/Users/d068290/go/src/github.com/gardener/gardenctl/vendor/github.com/spf13/cobra/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/d068290/go/src/github.com/gardener/gardenctl/vendor/github.com/spf13/cobra/command.go:864
github.com/gardener/gardenctl/pkg/cmd.Execute()
	/Users/d068290/go/src/github.com/gardener/gardenctl/pkg/cmd/root.go:111 +0x3aa
main.main()
	/Users/d068290/go/src/github.com/gardener/gardenctl/cmd/gardenctl/main.go:20 +0x20
```

**Gardenctl Version (please complete the following information):**
 - Version/Commit [e.g. ba79e6e55ff4857011589d71e279d2d654c86713]

**Comment by tedteng** [comment]
I will have a look

**Comment by neo-liang-sap** [comment]
sorry i noticed this issue last week and plan to fix it when i'm back from vacation - a very quick fix is here https://github.com/gardener/gardenctl/pull/177
@dansible @tedteng FYI...
