### ISSUE TITLE
Segmentation fault on gardenctl target shoot <shoot>

### ISSUE THREAD

**Issue by morremeyer** [gardener/gardenctl#507]
**Describe the bug**
When using `gardenctl target shoot <shoot>`, `gardenctl` segfaults.

**To Reproduce**

1. Current targets:
2. 
```sh
❯ gardenctl get target
target:
- kind: garden
  name: botany
- kind: project
  name: mmeyer
```

2. Which command was entered [e.g. 'gardenctl show vpn-seed']

```sh
gardenctl target shoot vhs6ir7a0e
```

3. What was the output of the command 

```sh
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x14531e8]

goroutine 1 [running]:
github.com/gardener/gardenctl/pkg/cmd.targetShoot(0x193df40, 0x2551220, 0x193df60, 0x2551220, 0x0, 0x0, 0x0, 0x0, 0xc00080b374, 0xa, ...)
	/home/runner/work/gardenctl/gardenctl/pkg/cmd/target.go:572 +0x398
github.com/gardener/gardenctl/pkg/cmd.shootWrapper(0x193df40, 0x2551220, 0x193df60, 0x2551220, 0x193dee0, 0x2551220, 0x193f500, 0xc00000e010, 0x193f520, 0xc00000e018, ...)
	/home/runner/work/gardenctl/gardenctl/pkg/cmd/target.go:1103 +0x520
github.com/gardener/gardenctl/pkg/cmd.NewTargetCmd.func1(0xc00033f080, 0xc000257760, 0x2, 0x2, 0x0, 0x0)
	/home/runner/work/gardenctl/gardenctl/pkg/cmd/target.go:128 +0x2363
github.com/spf13/cobra.(*Command).execute(0xc00033f080, 0xc0002576a0, 0x2, 0x2, 0xc00033f080, 0xc0002576a0)
	/home/runner/work/gardenctl/gardenctl/vendor/github.com/spf13/cobra/command.go:840 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0x2513b80, 0x1b, 0xc000047cc0, 0x34)
	/home/runner/work/gardenctl/gardenctl/vendor/github.com/spf13/cobra/command.go:945 +0x317
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/work/gardenctl/gardenctl/vendor/github.com/spf13/cobra/command.go:885
github.com/gardener/gardenctl/pkg/cmd.Execute()
	/home/runner/work/gardenctl/gardenctl/pkg/cmd/root.go:117 +0x3ba
main.main()
	/home/runner/work/gardenctl/gardenctl/cmd/gardenctl/main.go:20 +0x20
``` 

**Expected behavior**
No segfault, shoot gets targeted.

**Gardenctl Version (please complete the following information):** v0.24.1

**Additional context**
The shoot to be targeted is not fully set up yet when the command is issued - the command was issued in order to debug why the worker nodes are not getting ready.

**Comment by tedteng** [comment]
Hi @morremeyer,  I couldn't reproduce your issue.
Could you help check following, 
```
❯ gardenctl get target
target:
- kind: garden
  name: botany
- kind: project
  name: mmeyer
```
Could you help me verify whether able to execute the command and `vhs6ir7a0e` is it exist from the result after your target `garden` and `project`
```
gardenctl ls shoots
```

and one more thing, Which roles are you from the Member page in your project? `Owner`,`admin`,`viewer` and `UAM`.
